### ISSUE TITLE
Pin GitHub Actions versions using pinact

### ISSUE THREAD

**Issue by mkusaka** [mkusaka/llmstxt#9]
## AS IS (Current State)

Currently, our GitHub Actions workflows use version references like `@v4` or `@v3` which are mutable tags. This poses security and reliability risks as these tags can be changed by the action maintainers.

```yaml
- uses: actions/checkout@v4
- uses: actions/setup-node@v3
```

## TO BE (Desired State)

Pin all GitHub Actions to specific commit hashes to ensure immutability and security, following GitHub security best practices.

```yaml
- uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v4.2.2
- uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
```

## Implementation Plan

1. Install and configure pinact to automatically pin GitHub Actions versions
2. Set up a GitHub workflow to run pinact on PRs and/or periodically
3. Update existing workflows to use pinned versions
4. Configure validation to ensure all actions remain pinned

## Checklist

- [ ] Install pinact CLI or set up pinact-action
- [ ] Create `.pinact.yaml` configuration file
- [ ] Run pinact to pin all current GitHub Actions
- [ ] Set up GitHub workflow to run pinact automatically
- [ ] Add validation to CI to ensure actions remain pinned
- [ ] Update documentation with pinning requirements

### pinact Installation

```bash
# Using Go
go install github.com/suzuki-shunsuke/pinact/cmd/pinact@latest

# Using Homebrew
brew install suzuki-shunsuke/tap/pinact
```

### Configuration File

Create `.pinact.yaml` with the following content:

```yaml
version: 3
files:
  - pattern: .github/workflows/*.yml
  - pattern: .github/workflows/*.yaml
```

### GitHub Workflow

Create a workflow to automatically pin actions:

```yaml
name: Pin GitHub Actions
on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v4.2.2
        with:
          persist-credentials: false
      
      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@d735505f3decf76fca3fdbb4c952e5b3eba0ffdd # v0.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

### Benefits

- **Security**: Prevents supply chain attacks through mutable tags
- **Reliability**: Ensures consistent behavior across builds
- **Auditability**: Makes it clear which exact version of an action is being used
- **Automation**: pinact can automatically update pins when new versions are available
